baseURL = 'https://nutshellengineering.github.io/uuid/'
languageCode = 'en-gb'
title = 'uuid'
disablePathToLower = true
defaultContentLanguage = "en"

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'
BookToC = true
BookSearch = false
BookLogo = 'logo.png'
images = ["https://raw.githubusercontent.com/NutshellEngineering/images/refs/heads/main/elliot/tvos/app_store_icon.png?token=GHSAT0AAAAAADBLHDL5OPBH4KXUUMOBD35U2C5C7KQ"]

[languages]
[languages.en]
languageName = "English"
weight = 1

[markup.goldmark.renderer]
unsafe = true

[markup]
[markup.highlight]
style = "github"
